dirs:
  - ./
ignorePatterns:
  - pattern: '^http://localhost*'
replacementPatterns:
  - pattern: "https://www.ibm.com/docs"
    replacement: 'https://ibmdocs-test.dcs.ibm.com/docs'
aliveStatusCodes:
  - 200
  - 206
  - 429
useGitIgnore: true