services:
  odm:
    image: icr.io/cpopen/odm-k8s/odm:9.6
    hostname: odm
    container_name: odm
    environment:
      - LICENSE=accept
    healthcheck:
      test: curl -k -f http://localhost:9060/decisioncenter/healthCheck || exit 1
      interval: 5s
      timeout: 10s
      retries: 30
      start_period: 10s
    ports:
      - 9060:9060
  triggerDeployment:
    image: icr.io/cpopen/odm-k8s/odm:9.6
    container_name: upload_materials
    depends_on:
      odm:
        condition: service_healthy
    volumes:
      - ./samples:/samples
    entrypoint: >
      sh -c "cd /samples/ && ./deploy_demo_materials.sh basic http://odm:9060/decisioncenter-api http://localhost:9060/res odmAdmin odmAdmin &&  echo '✅ ODM Ready for MCP Server' "
    restart: "no"
  
  ibm-odm-decision-mcp-server:
    image: ibm-odm-decision-mcp-server:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILDKIT_INLINE_CACHE: 0
      no_cache: true
    container_name: ibm-odm-decision-mcp-server
    depends_on:
      odm:
        condition: service_healthy
    ports:
      - 3001:3000
    secrets:
      - odm_password
    environment:
      - TRANSPORT=streamable-http
      - LOG_LEVEL=INFO
      - TRACE_ENABLE=True
      - TRACE_MAXSIZE=200
      - TRACES_DIR=/home/worker/traces
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        exec ibm-odm-decision-mcp-server \
          --url http://odm:9060/res \
          --username resDeployer \
          --password "$(cat /run/secrets/odm_password)"
    profiles: [ibm-odm-decision-mcp-server]

  ibm-odm-decision-mcp-server-ubi:
    image: ibm-odm-decision-mcp-server-ubi:latest
    build:
      context: .
      dockerfile: Dockerfile-ubi
      args:
        BUILDKIT_INLINE_CACHE: 0
      no_cache: true
    container_name: ibm-odm-decision-mcp-server-ubi
    depends_on:
      odm:
        condition: service_healthy
    ports:
      - 3001:3000
    secrets:
      - odm_password
    environment:
      - TRANSPORT=streamable-http
      - VERIFY_SSL=True
      - VERIFY_SSL_HOSTNAME=True
      - LOG_LEVEL=INFO
      - TRACE_ENABLE=True
      - TRACE_MAXSIZE=200
      - TRACES_DIR=/home/worker/traces
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        exec ibm-odm-decision-mcp-server \
          --url http://odm:9060/res \
          --username resDeployer \
          --password "$(cat /run/secrets/odm_password)"
    profiles: [ibm-odm-decision-mcp-server-ubi]

  amd64_arm64:
    image: $REPOSITORY/$IMAGE:$TAG
    build:
      context: .
      dockerfile: Dockerfile-ubi
      platforms:
        - "linux/amd64"
      args:
        BUILDKIT_INLINE_CACHE: 0
        VERSION: $VERSION
      no_cache: true

secrets:
  odm_password:
    environment: ODM_PASSWORD